# Generated by Django 2.1.7 on 2019-04-20 15:38

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('TitExc', 'Prof. Titular Exclusiva'), ('TitSmx', 'Prof. Titular Semiexclusiva'), ('TitSim', 'Prof. Titular Simple'), ('AsoExc', 'Prof. Asociado Exclusiva'), ('AsoSmx', 'Prof. Asociado Semiexclusiva'), ('AsoSim', 'Prof. Asociado Simple'), ('AdjExc', 'Prof. Adjunto Exclusiva'), ('AdjSmx', 'Prof. Adjunto Semiexclusiva'), ('AdjSim', 'Prof. Adjunto Simple'), ('JTPExc', 'Jefe de Trabajos Prácticos Exclusiva'), ('JTPSmx', 'Jefe de Trabajos Prácticos Semiexclusiva'), ('JTPSim', 'Jefe de Trabajos Prácticos Simple'), ('Ay1Exc', 'Ayudante de 1ra Exclusiva'), ('Ay1Smx', 'Ayudante de 1ra Semiexclusiva'), ('Ay1Sim', 'Ayudante de 1ra Simple'), ('Ay2Exc', 'Ayudante de 2da Exclusiva'), ('Ay2Smx', 'Ayudante de 2da Semiexclusiva'), ('Ay2Sim', 'Ayudante de 2da Simple')], max_length=6)),
                ('anno', models.IntegerField()),
                ('cuatrimestre', models.CharField(choices=[('P', '1'), ('S', '2'), ('V', 'V')], max_length=1)),
            ],
            options={
                'verbose_name': 'carga docente',
                'verbose_name_plural': 'cargas docentes',
            },
        ),
        migrations.CreateModel(
            name='CuatrimestreDocente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField()),
                ('cuatrimestre', models.CharField(choices=[('P', '1'), ('S', '2'), ('V', 'V')], max_length=1)),
                ('cargas', models.IntegerField()),
            ],
            options={
                'verbose_name': 'info cuatrimestral del docente',
                'verbose_name_plural': 'informaciones cuatrimestrales',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\ \\d+)*\\Z'), code='invalid', message=None)])),
                ('email', models.EmailField(max_length=254)),
                ('cargos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('TitExc', 'Prof. Titular Exclusiva'), ('TitSmx', 'Prof. Titular Semiexclusiva'), ('TitSim', 'Prof. Titular Simple'), ('AsoExc', 'Prof. Asociado Exclusiva'), ('AsoSmx', 'Prof. Asociado Semiexclusiva'), ('AsoSim', 'Prof. Asociado Simple'), ('AdjExc', 'Prof. Adjunto Exclusiva'), ('AdjSmx', 'Prof. Adjunto Semiexclusiva'), ('AdjSim', 'Prof. Adjunto Simple'), ('JTPExc', 'Jefe de Trabajos Prácticos Exclusiva'), ('JTPSmx', 'Jefe de Trabajos Prácticos Semiexclusiva'), ('JTPSim', 'Jefe de Trabajos Prácticos Simple'), ('Ay1Exc', 'Ayudante de 1ra Exclusiva'), ('Ay1Smx', 'Ayudante de 1ra Semiexclusiva'), ('Ay1Sim', 'Ayudante de 1ra Simple'), ('Ay2Exc', 'Ayudante de 2da Exclusiva'), ('Ay2Smx', 'Ayudante de 2da Semiexclusiva'), ('Ay2Sim', 'Ayudante de 2da Simple')], max_length=6), size=2)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lu', 'Lunes'), ('Ma', 'Martes'), ('Mi', 'Miércoles'), ('Ju', 'Jueves'), ('Vi', 'Viernes')], max_length=2)),
                ('comienzo', models.TimeField(verbose_name='comienzo')),
                ('final', models.TimeField(verbose_name='final')),
                ('aula', models.CharField(blank=True, max_length=5, null=True)),
                ('pabellon', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('obligatoriedad', models.CharField(choices=[('B', 'obligatoria'), ('R', 'optativa regular'), ('N', 'optativa no regular')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField()),
                ('cuatrimestre', models.CharField(choices=[('P', '1'), ('S', '2'), ('V', 'V')], max_length=1)),
                ('numero', models.IntegerField()),
                ('subnumero', models.CharField(blank=True, max_length=6)),
                ('tipo', models.CharField(choices=[('T', 'Teórica'), ('P', 'Práctica'), ('A', 'Teórico-Práctica')], max_length=1)),
                ('necesidad_prof', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(15)])),
                ('necesidad_jtp', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(15)])),
                ('necesidad_ay1', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(15)])),
                ('necesidad_ay2', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(15)])),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.Materia')),
            ],
        ),
        migrations.AddField(
            model_name='horario',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.Turno'),
        ),
        migrations.AddField(
            model_name='cuatrimestredocente',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.Docente'),
        ),
        migrations.AddField(
            model_name='carga',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.Docente'),
        ),
        migrations.AddField(
            model_name='carga',
            name='turno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materias.Turno'),
        ),
    ]
