# Generated by Django 2.1.5 on 2019-01-07 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('cargo', models.CharField(max_length=20)),
                ('cargas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(verbose_name='dia primera clase')),
                ('comienzo', models.TimeField(verbose_name='comienzo')),
                ('final', models.TimeField(verbose_name='final')),
                ('aula', models.IntegerField()),
                ('pabellon', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('tipo', models.CharField(max_length=1)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.Materia')),
            ],
        ),
        migrations.AddField(
            model_name='horario',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.Turno'),
        ),
        migrations.AddField(
            model_name='carga',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.Docente'),
        ),
        migrations.AddField(
            model_name='carga',
            name='turno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materias.Turno'),
        ),
    ]
