# Generated by Django 2.1.7 on 2019-03-19 22:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    replaces = [('materias', '0001_initial')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('Tit', 'Prof. Titular'), ('Aso', 'Prof. Asociado'), ('Adj', 'Prof. Adjunto'), ('JTP', 'Jefe de Trabajos Prácticos'), ('Ay1', 'Ayudante de 1ra'), ('Ay2', 'Ayudante de 2da')], max_length=3)),
            ],
            options={
                'verbose_name': 'carga docente',
                'verbose_name_plural': 'cargas docentes',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\ \\d+)*\\Z'), code='invalid', message=None)])),
                ('email', models.EmailField(max_length=254)),
                ('cargo', models.CharField(choices=[('Tit', 'Prof. Titular'), ('Aso', 'Prof. Asociado'), ('Adj', 'Prof. Adjunto'), ('JTP', 'Jefe de Trabajos Prácticos'), ('Ay1', 'Ayudante de 1ra'), ('Ay2', 'Ayudante de 2da')], max_length=3)),
                ('cargas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lu', 'Lunes'), ('Ma', 'Martes'), ('Mi', 'Miércoles'), ('Ju', 'Jueves'), ('Vi', 'Viernes')], max_length=2)),
                ('comienzo', models.TimeField(verbose_name='comienzo')),
                ('final', models.TimeField(verbose_name='final')),
                ('aula', models.CharField(blank=True, max_length=5, null=True)),
                ('pabellon', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('obligatoriedad', models.CharField(choices=[('B', 'obligatoria'), ('R', 'optativa regular'), ('N', 'optativa no regular')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField()),
                ('cuatrimestre', models.CharField(choices=[('P', '1'), ('S', '2'), ('V', 'V')], max_length=1)),
                ('numero', models.IntegerField()),
                ('subnumero', models.CharField(blank=True, max_length=6)),
                ('tipo', models.CharField(choices=[('T', 'Teórica'), ('P', 'Práctica'), ('A', 'Teórico-Práctica')], max_length=1)),
                ('necesidades', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.Materia')),
            ],
        ),
        migrations.AddField(
            model_name='horario',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.Turno'),
        ),
        migrations.AddField(
            model_name='carga',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.Docente'),
        ),
        migrations.AddField(
            model_name='carga',
            name='turno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materias.Turno'),
        ),
    ]
