# Generated by Django 2.1.7 on 2019-03-10 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuatrimestreDocente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField()),
                ('cuatrimestre', models.CharField(choices=[('P', '1'), ('S', '2'), ('V', 'V')], max_length=1)),
                ('cargas', models.IntegerField()),
            ],
            options={
                'verbose_name': 'info cuatrimestral del docente',
                'verbose_name_plural': 'informaciones cuatrimestrales',
            },
        ),
        migrations.RemoveField(
            model_name='docente',
            name='cargas',
        ),
        migrations.AddField(
            model_name='cuatrimestredocente',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.Docente'),
        ),
    ]
