# Generated by Django 2.1.5 on 2019-01-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carga',
            options={'verbose_name': 'carga docente', 'verbose_name_plural': 'cargas docentes'},
        ),
        migrations.AlterField(
            model_name='horario',
            name='dia',
            field=models.CharField(max_length=2),
        ),
    ]
