# Generated by Django 2.1.7 on 2019-04-21 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materias', '0002_historicalturno'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCarga',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('TitExc', 'Prof. Titular Exclusiva'), ('TitSmx', 'Prof. Titular Semiexclusiva'), ('TitSim', 'Prof. Titular Simple'), ('AsoExc', 'Prof. Asociado Exclusiva'), ('AsoSmx', 'Prof. Asociado Semiexclusiva'), ('AsoSim', 'Prof. Asociado Simple'), ('AdjExc', 'Prof. Adjunto Exclusiva'), ('AdjSmx', 'Prof. Adjunto Semiexclusiva'), ('AdjSim', 'Prof. Adjunto Simple'), ('JTPExc', 'Jefe de Trabajos Prácticos Exclusiva'), ('JTPSmx', 'Jefe de Trabajos Prácticos Semiexclusiva'), ('JTPSim', 'Jefe de Trabajos Prácticos Simple'), ('Ay1Exc', 'Ayudante de 1ra Exclusiva'), ('Ay1Smx', 'Ayudante de 1ra Semiexclusiva'), ('Ay1Sim', 'Ayudante de 1ra Simple'), ('Ay2Exc', 'Ayudante de 2da Exclusiva'), ('Ay2Smx', 'Ayudante de 2da Semiexclusiva'), ('Ay2Sim', 'Ayudante de 2da Simple')], max_length=6)),
                ('anno', models.IntegerField()),
                ('cuatrimestre', models.CharField(choices=[('P', '1'), ('S', '2'), ('V', 'V')], max_length=1)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('docente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='materias.Docente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('turno', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='materias.Turno')),
            ],
            options={
                'verbose_name': 'historical carga docente',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
