# Generated by Django 2.1.7 on 2019-03-14 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0002_auto_20190310_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='necesidades',
        ),
        migrations.AddField(
            model_name='turno',
            name='necesidad_ay1',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turno',
            name='necesidad_ay2',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turno',
            name='necesidad_jtp',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turno',
            name='necesidad_prof',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
