# Generated by Django 2.1.7 on 2019-03-14 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0003_auto_20190313_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='necesidad_ay1',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AlterField(
            model_name='turno',
            name='necesidad_ay2',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AlterField(
            model_name='turno',
            name='necesidad_jtp',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AlterField(
            model_name='turno',
            name='necesidad_prof',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(15)]),
        ),
    ]
