# Generated by Django 2.1.5 on 2019-01-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0003_auto_20190107_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='cargo',
            field=models.CharField(choices=[('Tit', 'Prof. Titular'), ('Aso', 'Prof. Asociado'), ('Adj', 'Prof. Adjunto'), ('JTP', 'Jefe de Trabajos Prácticos'), ('Ay1', 'Ayudante de 1ra'), ('Ay2', 'Ayudante de 2da')], max_length=3),
        ),
        migrations.AlterField(
            model_name='turno',
            name='tipo',
            field=models.CharField(choices=[('T', 'Teórico'), ('P', 'Práctico'), ('A', 'Teórico/Práctico')], max_length=1),
        ),
    ]
