# Generated by Django 2.1.5 on 2019-01-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0004_auto_20190107_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='cargo',
            field=models.CharField(choices=[('Tit', 'Prof. Titular'), ('Aso', 'Prof. Asociado'), ('Adj', 'Prof. Adjunto'), ('JTP', 'Jefe de Trabajos Prácticos'), ('Ay1', 'Ayudante de 1ra'), ('Ay2', 'Ayudante de 2da')], default='JTP', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docente',
            name='email',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docente',
            name='telefono',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
