# Generated by Django 2.1.7 on 2019-03-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0004_auto_20190314_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
    ]
