# Generated by Django 2.1.5 on 2019-01-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0005_auto_20190108_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='anno',
            field=models.IntegerField(default=2018),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materia',
            name='cuatrimestre',
            field=models.CharField(choices=[('P', '1'), ('S', '2'), ('V', 'Verano')], default='1', max_length=1),
            preserve_default=False,
        ),
    ]
