# Generated by Django 2.1.7 on 2019-04-29 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0005_auto_20190428_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuatrimestredocente',
            name='docente',
        ),
        migrations.DeleteModel(
            name='CuatrimestreDocente',
        ),
    ]
