# Generated by Django 2.1.5 on 2019-01-09 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0006_auto_20190108_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='obligatoriedad',
            field=models.CharField(choices=[('B', 'obligatoria'), ('R', 'optativa regular'), ('N', 'optativa no regular')], default='B', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materia',
            name='cuatrimestre',
            field=models.CharField(choices=[('P', '1'), ('S', '2'), ('V', 'V')], max_length=1),
        ),
    ]
