# Generated by Django 2.1.7 on 2019-05-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0006_auto_20190428_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalturno',
            name='dificil_de_cubrir',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turno',
            name='dificil_de_cubrir',
            field=models.BooleanField(default=False),
        ),
    ]
