# Generated by Django 2.1.7 on 2019-04-07 13:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0006_auto_20190407_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='cargo',
            field=models.CharField(choices=[('TitExc', 'Prof. Titular Exclusiva'), ('TitSmx', 'Prof. Titular Semiexclusiva'), ('TitSim', 'Prof. Titular Simple'), ('AsoExc', 'Prof. Asociado Exclusiva'), ('AsoSmx', 'Prof. Asociado Semiexclusiva'), ('AsoSim', 'Prof. Asociado Simple'), ('AdjExc', 'Prof. Adjunto Exclusiva'), ('AdjSmx', 'Prof. Adjunto Semiexclusiva'), ('AdjSim', 'Prof. Adjunto Simple'), ('JTPExc', 'Jefe de Trabajos Prácticos Exclusiva'), ('JTPSmx', 'Jefe de Trabajos Prácticos Semiexclusiva'), ('JTPSim', 'Jefe de Trabajos Prácticos Simple'), ('Ay1Exc', 'Ayudante de 1ra Exclusiva'), ('Ay1Smx', 'Ayudante de 1ra Semiexclusiva'), ('Ay1Sim', 'Ayudante de 1ra Simple'), ('Ay2Exc', 'Ayudante de 2da Exclusiva'), ('Ay2Smx', 'Ayudante de 2da Semiexclusiva'), ('Ay2Sim', 'Ayudante de 2da Simple')], max_length=6),
        ),
        migrations.AlterField(
            model_name='docente',
            name='cargos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('TitExc', 'Prof. Titular Exclusiva'), ('TitSmx', 'Prof. Titular Semiexclusiva'), ('TitSim', 'Prof. Titular Simple'), ('AsoExc', 'Prof. Asociado Exclusiva'), ('AsoSmx', 'Prof. Asociado Semiexclusiva'), ('AsoSim', 'Prof. Asociado Simple'), ('AdjExc', 'Prof. Adjunto Exclusiva'), ('AdjSmx', 'Prof. Adjunto Semiexclusiva'), ('AdjSim', 'Prof. Adjunto Simple'), ('JTPExc', 'Jefe de Trabajos Prácticos Exclusiva'), ('JTPSmx', 'Jefe de Trabajos Prácticos Semiexclusiva'), ('JTPSim', 'Jefe de Trabajos Prácticos Simple'), ('Ay1Exc', 'Ayudante de 1ra Exclusiva'), ('Ay1Smx', 'Ayudante de 1ra Semiexclusiva'), ('Ay1Sim', 'Ayudante de 1ra Simple'), ('Ay2Exc', 'Ayudante de 2da Exclusiva'), ('Ay2Smx', 'Ayudante de 2da Semiexclusiva'), ('Ay2Sim', 'Ayudante de 2da Simple')], max_length=6), size=2),
        ),
    ]
