# Generated by Django 2.1.5 on 2019-01-09 02:11

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0007_auto_20190108_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='necesidades',
            field=models.CharField(default=(1, 0, 0), max_length=5, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='docente',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='docente',
            name='telefono',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\ \\d+)*\\Z'), code='invalid', message=None)]),
        ),
    ]
