# Generated by Django 2.1.9 on 2019-06-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('materias', '0008_auto_20190629_0847'), ('materias', '0009_auto_20190629_1319'), ('materias', '0010_auto_20190629_1322')]

    dependencies = [
        ('materias', '0007_auto_20190504_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhorario',
            name='pabellon',
            field=models.CharField(blank=True, choices=[('1', 'Uno'), ('2', 'Dos'), ('I', 'Industrias'), ('0', 'Cero_infinito')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='pabellon',
            field=models.CharField(blank=True, choices=[('1', 'Uno'), ('2', 'Dos'), ('I', 'Industrias'), ('0', 'Cero_infinito')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhorario',
            name='pabellon',
            field=models.CharField(blank=True, choices=[('1', 'I'), ('2', 'II'), ('I', 'Ind'), ('0', '0+∞')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='pabellon',
            field=models.CharField(blank=True, choices=[('1', 'I'), ('2', 'II'), ('I', 'Ind'), ('0', '0+∞')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhorario',
            name='pabellon',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('I', 'Ind'), ('0', '0+∞')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='pabellon',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('I', 'Ind'), ('0', '0+∞')], max_length=1, null=True),
        ),
    ]
