# Generated by Django 2.1.7 on 2019-04-11 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0007_auto_20190407_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='anno',
            field=models.IntegerField(default=2019),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carga',
            name='cuatrimestre',
            field=models.CharField(choices=[('P', '1'), ('S', '2'), ('V', 'V')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
