# Generated by Django 2.1.9 on 2019-06-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0007_auto_20190504_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhorario',
            name='pabellon',
            field=models.CharField(blank=True, choices=[('1', 'Uno'), ('2', 'Dos'), ('I', 'Industrias'), ('0', 'Cero_infinito')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='pabellon',
            field=models.CharField(blank=True, choices=[('1', 'Uno'), ('2', 'Dos'), ('I', 'Industrias'), ('0', 'Cero_infinito')], max_length=1, null=True),
        ),
    ]
