# Generated by Django 2.1.5 on 2019-01-09 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0008_auto_20190108_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='aula',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='pabellon',
            field=models.IntegerField(null=True),
        ),
    ]
