# Generated by Django 2.1.9 on 2019-06-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0008_auto_20190629_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhorario',
            name='pabellon',
            field=models.CharField(blank=True, choices=[('1', 'I'), ('2', 'II'), ('I', 'Ind'), ('0', '0+∞')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='pabellon',
            field=models.CharField(blank=True, choices=[('1', 'I'), ('2', 'II'), ('I', 'Ind'), ('0', '0+∞')], max_length=1, null=True),
        ),
    ]
