# Generated by Django 2.1.9 on 2019-06-30 13:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0008_auto_20190629_0847_squashed_0010_auto_20190629_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='historicaldocente',
            name='nombre',
        ),
        migrations.AddField(
            model_name='docente',
            name='na_apellido',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docente',
            name='na_nombre',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldocente',
            name='na_apellido',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldocente',
            name='na_nombre',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carga',
            name='cargo',
            field=models.CharField(choices=[('EmeExc', 'Prof. Emerito Exclusiva'), ('EmeSmx', 'Prof. Emerito Semiexclusiva'), ('EmeSim', 'Prof. Emerito Simple'), ('HonExc', 'Prof. Honorario Exclusiva'), ('HonSmx', 'Prof. Honorario Semiexclusiva'), ('HonSim', 'Prof. Honorario Simple'), ('ConExc', 'Prof. Consulto Exclusiva'), ('ConSmx', 'Prof. Consulto Semiexclusiva'), ('ConSim', 'Prof. Consulto Simple'), ('PleExc', 'Prof. Plenario Exclusiva'), ('PleSmx', 'Prof. Plenario Semiexclusiva'), ('PleSim', 'Prof. Plenario Simple'), ('VisExc', 'Prof. Visitante Exclusiva'), ('VisSmx', 'Prof. Visitante Semiexclusiva'), ('VisSim', 'Prof. Visitante Simple'), ('TitExc', 'Prof. Titular Exclusiva'), ('TitSmx', 'Prof. Titular Semiexclusiva'), ('TitSim', 'Prof. Titular Simple'), ('AsoExc', 'Prof. Asociado Exclusiva'), ('AsoSmx', 'Prof. Asociado Semiexclusiva'), ('AsoSim', 'Prof. Asociado Simple'), ('AdjExc', 'Prof. Adjunto Exclusiva'), ('AdjSmx', 'Prof. Adjunto Semiexclusiva'), ('AdjSim', 'Prof. Adjunto Simple'), ('JTPExc', 'Jefe de Trabajos Prácticos Exclusiva'), ('JTPSmx', 'Jefe de Trabajos Prácticos Semiexclusiva'), ('JTPSim', 'Jefe de Trabajos Prácticos Simple'), ('Ay1Exc', 'Ayudante de 1ra Exclusiva'), ('Ay1Smx', 'Ayudante de 1ra Semiexclusiva'), ('Ay1Sim', 'Ayudante de 1ra Simple'), ('Ay2Exc', 'Ayudante de 2da Exclusiva'), ('Ay2Smx', 'Ayudante de 2da Semiexclusiva'), ('Ay2Sim', 'Ayudante de 2da Simple')], max_length=6),
        ),
        migrations.AlterField(
            model_name='docente',
            name='cargos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('EmeExc', 'Prof. Emerito Exclusiva'), ('EmeSmx', 'Prof. Emerito Semiexclusiva'), ('EmeSim', 'Prof. Emerito Simple'), ('HonExc', 'Prof. Honorario Exclusiva'), ('HonSmx', 'Prof. Honorario Semiexclusiva'), ('HonSim', 'Prof. Honorario Simple'), ('ConExc', 'Prof. Consulto Exclusiva'), ('ConSmx', 'Prof. Consulto Semiexclusiva'), ('ConSim', 'Prof. Consulto Simple'), ('PleExc', 'Prof. Plenario Exclusiva'), ('PleSmx', 'Prof. Plenario Semiexclusiva'), ('PleSim', 'Prof. Plenario Simple'), ('VisExc', 'Prof. Visitante Exclusiva'), ('VisSmx', 'Prof. Visitante Semiexclusiva'), ('VisSim', 'Prof. Visitante Simple'), ('TitExc', 'Prof. Titular Exclusiva'), ('TitSmx', 'Prof. Titular Semiexclusiva'), ('TitSim', 'Prof. Titular Simple'), ('AsoExc', 'Prof. Asociado Exclusiva'), ('AsoSmx', 'Prof. Asociado Semiexclusiva'), ('AsoSim', 'Prof. Asociado Simple'), ('AdjExc', 'Prof. Adjunto Exclusiva'), ('AdjSmx', 'Prof. Adjunto Semiexclusiva'), ('AdjSim', 'Prof. Adjunto Simple'), ('JTPExc', 'Jefe de Trabajos Prácticos Exclusiva'), ('JTPSmx', 'Jefe de Trabajos Prácticos Semiexclusiva'), ('JTPSim', 'Jefe de Trabajos Prácticos Simple'), ('Ay1Exc', 'Ayudante de 1ra Exclusiva'), ('Ay1Smx', 'Ayudante de 1ra Semiexclusiva'), ('Ay1Sim', 'Ayudante de 1ra Simple'), ('Ay2Exc', 'Ayudante de 2da Exclusiva'), ('Ay2Smx', 'Ayudante de 2da Semiexclusiva'), ('Ay2Sim', 'Ayudante de 2da Simple')], max_length=6), size=2),
        ),
        migrations.AlterField(
            model_name='historicalcarga',
            name='cargo',
            field=models.CharField(choices=[('EmeExc', 'Prof. Emerito Exclusiva'), ('EmeSmx', 'Prof. Emerito Semiexclusiva'), ('EmeSim', 'Prof. Emerito Simple'), ('HonExc', 'Prof. Honorario Exclusiva'), ('HonSmx', 'Prof. Honorario Semiexclusiva'), ('HonSim', 'Prof. Honorario Simple'), ('ConExc', 'Prof. Consulto Exclusiva'), ('ConSmx', 'Prof. Consulto Semiexclusiva'), ('ConSim', 'Prof. Consulto Simple'), ('PleExc', 'Prof. Plenario Exclusiva'), ('PleSmx', 'Prof. Plenario Semiexclusiva'), ('PleSim', 'Prof. Plenario Simple'), ('VisExc', 'Prof. Visitante Exclusiva'), ('VisSmx', 'Prof. Visitante Semiexclusiva'), ('VisSim', 'Prof. Visitante Simple'), ('TitExc', 'Prof. Titular Exclusiva'), ('TitSmx', 'Prof. Titular Semiexclusiva'), ('TitSim', 'Prof. Titular Simple'), ('AsoExc', 'Prof. Asociado Exclusiva'), ('AsoSmx', 'Prof. Asociado Semiexclusiva'), ('AsoSim', 'Prof. Asociado Simple'), ('AdjExc', 'Prof. Adjunto Exclusiva'), ('AdjSmx', 'Prof. Adjunto Semiexclusiva'), ('AdjSim', 'Prof. Adjunto Simple'), ('JTPExc', 'Jefe de Trabajos Prácticos Exclusiva'), ('JTPSmx', 'Jefe de Trabajos Prácticos Semiexclusiva'), ('JTPSim', 'Jefe de Trabajos Prácticos Simple'), ('Ay1Exc', 'Ayudante de 1ra Exclusiva'), ('Ay1Smx', 'Ayudante de 1ra Semiexclusiva'), ('Ay1Sim', 'Ayudante de 1ra Simple'), ('Ay2Exc', 'Ayudante de 2da Exclusiva'), ('Ay2Smx', 'Ayudante de 2da Semiexclusiva'), ('Ay2Sim', 'Ayudante de 2da Simple')], max_length=6),
        ),
        migrations.AlterField(
            model_name='historicaldocente',
            name='cargos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('EmeExc', 'Prof. Emerito Exclusiva'), ('EmeSmx', 'Prof. Emerito Semiexclusiva'), ('EmeSim', 'Prof. Emerito Simple'), ('HonExc', 'Prof. Honorario Exclusiva'), ('HonSmx', 'Prof. Honorario Semiexclusiva'), ('HonSim', 'Prof. Honorario Simple'), ('ConExc', 'Prof. Consulto Exclusiva'), ('ConSmx', 'Prof. Consulto Semiexclusiva'), ('ConSim', 'Prof. Consulto Simple'), ('PleExc', 'Prof. Plenario Exclusiva'), ('PleSmx', 'Prof. Plenario Semiexclusiva'), ('PleSim', 'Prof. Plenario Simple'), ('VisExc', 'Prof. Visitante Exclusiva'), ('VisSmx', 'Prof. Visitante Semiexclusiva'), ('VisSim', 'Prof. Visitante Simple'), ('TitExc', 'Prof. Titular Exclusiva'), ('TitSmx', 'Prof. Titular Semiexclusiva'), ('TitSim', 'Prof. Titular Simple'), ('AsoExc', 'Prof. Asociado Exclusiva'), ('AsoSmx', 'Prof. Asociado Semiexclusiva'), ('AsoSim', 'Prof. Asociado Simple'), ('AdjExc', 'Prof. Adjunto Exclusiva'), ('AdjSmx', 'Prof. Adjunto Semiexclusiva'), ('AdjSim', 'Prof. Adjunto Simple'), ('JTPExc', 'Jefe de Trabajos Prácticos Exclusiva'), ('JTPSmx', 'Jefe de Trabajos Prácticos Semiexclusiva'), ('JTPSim', 'Jefe de Trabajos Prácticos Simple'), ('Ay1Exc', 'Ayudante de 1ra Exclusiva'), ('Ay1Smx', 'Ayudante de 1ra Semiexclusiva'), ('Ay1Sim', 'Ayudante de 1ra Simple'), ('Ay2Exc', 'Ayudante de 2da Exclusiva'), ('Ay2Smx', 'Ayudante de 2da Semiexclusiva'), ('Ay2Sim', 'Ayudante de 2da Simple')], max_length=6), size=2),
        ),
    ]
