# Generated by Django 2.1.5 on 2019-01-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0009_auto_20190108_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='anno',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='cuatrimestre',
        ),
        migrations.AddField(
            model_name='turno',
            name='anno',
            field=models.IntegerField(default=2019),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turno',
            name='cuatrimestre',
            field=models.CharField(choices=[('P', '1'), ('S', '2'), ('V', 'V')], default='P', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='horario',
            name='aula',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='pabellon',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='tipo',
            field=models.CharField(choices=[('T', 'Teórica'), ('P', 'Práctica'), ('A', 'Teórico-Práctica')], max_length=1),
        ),
    ]
