# Generated by Django 2.1.9 on 2019-06-30 22:40

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0009_auto_20190630_1014'),
    ]

    operations = [
        CreateExtension(name='fuzzystrmatch'),
    ]
