# Generated by Django 2.1 on 2019-03-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0011_turno_subnumero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='aula',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
