# Generated by Django 2.1.10 on 2019-08-04 23:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0014_auto_20190728_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='telefono',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener +, -, números, espacios y tener entre 9 y 15 caracteres', regex='^\\+?[0-9 -]{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='historicaldocente',
            name='telefono',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener +, -, números, espacios y tener entre 9 y 15 caracteres', regex='^\\+?[0-9 -]{9,15}$')]),
        ),
    ]
