# Generated by Django 2.1.10 on 2019-08-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0015_auto_20190804_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carga',
            options={'ordering': ['cargo', 'docente__na_appellido', 'docente__na_nombre'], 'verbose_name': 'carga docente', 'verbose_name_plural': 'cargas docentes'},
        ),
        migrations.AlterModelOptions(
            name='docente',
            options={'ordering': ['cargos', 'na_apellido', 'na_nombre']},
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={'ordering': ['obligatoriedad', 'nombre']},
        ),
        migrations.AlterField(
            model_name='historicalmateria',
            name='obligatoriedad',
            field=models.CharField(choices=[('B', 'obligatoria'), ('R', 'optativa regular'), ('N', 'optativa no regular')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='materia',
            name='obligatoriedad',
            field=models.CharField(choices=[('B', 'obligatoria'), ('R', 'optativa regular'), ('N', 'optativa no regular')], default='N', max_length=1),
        ),
    ]
