# Generated by Django 2.1.15 on 2020-11-15 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0020_auto_20191109_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carga',
            options={'ordering': ['cargo', 'docente__na_apellido', 'docente__na_nombre'], 'verbose_name': 'carga docente', 'verbose_name_plural': 'cargas docentes'},
        ),
    ]
