# Generated by Django 2.1.15 on 2021-01-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0021_auto_20201115_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmateria',
            name='nombre',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nombre',
            field=models.CharField(max_length=160),
        ),
    ]
