# Generated by Django 2.2.20 on 2021-05-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0022_auto_20210117_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalturno',
            name='tipo',
            field=models.CharField(choices=[('T', 'Teórica'), ('P', 'Práctica'), ('A', 'Teórico-Práctica'), ('L', 'Laboratorio')], max_length=1),
        ),
        migrations.AlterField(
            model_name='turno',
            name='tipo',
            field=models.CharField(choices=[('T', 'Teórica'), ('P', 'Práctica'), ('A', 'Teórico-Práctica'), ('L', 'Laboratorio')], max_length=1),
        ),
    ]
