language: python
sudo: required
dist: xenial
python:
  - "3.7"
services:
  - postgresql

install:
  - pip install -r requirements.txt
  - git clone https://github.com/matiasg/allocation.git
  - pip install -e allocation
  - pip install -r allocation/requirements.txt
  - pip install coveralls

script:
  - coverage run --source=. manage.py test

after_success:
  - coveralls
