version: '3'

services:
  db:
    image: postgres
    volumes:
      - distribucion_pgdata:/var/lib/postgresql/data
    networks:
      - db_network
  web:
    image: distribucion
    volumes:
      - distribucion_pgdata:/var/lib/postgresql/data
      - static_volume:/codigo/distribucion/static
      - nginx_conf:/codigo/distribucion/nginx_conf
    working_dir: /codigo/distribucion
    command: gunicorn --chdir /codigo/distribucion/distribucion --bind :8000 distribucion.wsgi:application
    depends_on:
      - db
    networks:
      - nginx_network
      - db_network
  bash:
    image: distribucion
    volumes:
      - distribucion_pgdata:/var/lib/postgresql/data
      - ${PWD}/../sitio_anterior:/codigo/sitio_anterior
    command: /bin/bash
    depends_on:
      - db

  nginx:
    image: nginx:1.17.2-alpine
    ports:
      - 8000:80
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - static_volume:/codigo/distribucion/static
    depends_on:
      - web
    networks:
      - nginx_network

volumes:
  distribucion_pgdata:
    external: true
  static_volume:
  nginx_conf:

networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge
