version: '3'

services:
  db:
    image: postgres
    volumes:
      - distribucion_pgdata:/var/lib/postgresql/data
  web:
    image: distribucion
    volumes:
      - distribucion_pgdata:/var/lib/postgresql/data
    working_dir: /codigo/distribucion
    ports:
      - "8000:8000"
    command: python manage.py runserver --insecure 0.0.0.0:8000
    depends_on:
      - db
  bash:
    image: distribucion
    volumes:
      - distribucion_pgdata:/var/lib/postgresql/data
    command: /bin/bash
    depends_on:
      - db

volumes:
  distribucion_pgdata:
    external: true
