version: '3'

services:
  db:
    image: postgres
    volumes:
      - distribucion_pgdata:/var/lib/postgresql/data
    networks:
      - db_network
  web:
    image: distribucion
    volumes:
      - distribucion_pgdata:/var/lib/postgresql/data
      - static_volume:/codigo/distribucion/static
    working_dir: /codigo/distribucion
    command: gunicorn --chdir /codigo/distribucion/distribucion --bind :8000 distribucion.wsgi:application
    depends_on:
      - db
    networks:
      - nginx_network
      - db_network
  bash:
    image: distribucion
    volumes:
      - distribucion_pgdata:/var/lib/postgresql/data
    command: /bin/bash
    depends_on:
      - db

  nginx:
    image: nginx:1.17.2-alpine
    ports:
      - 8000:8000
      - 8443:8443
    volumes:
      - ./nginx_conf_de_repo:/etc/nginx/conf.d:ro
      - static_volume:/codigo/distribucion/static
    depends_on:
      - web
    networks:
      - nginx_network
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

volumes:
  distribucion_pgdata:
    external: true
  static_volume:

networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge
