version: '3'

services:
  #db:
  #  image: postgres
  web:
    build: .
    environment:
      - DB_NAME=${DB_NAME:-db.sqlite}
    volumes:
      - "${DB_PATH:-/usr/local/share}:/db"
    working_dir: /codigo/distribucion
    ports:
      - "8000:8000"
    command: python manage.py runserver --insecure 0.0.0.0:8000
    #depends_on:
    #  - db
  bash:
    build: .
    environment:
      - DB_NAME=${DB_NAME:-db.sqlite}
    volumes:
      - "${DB_PATH:-/usr/local/share}:/db"
    command: /bin/bash
