RUN apt-get update && apt-get install -y git

RUN git clone https://github.com/matiasg/distribucion.git

RUN cp distribucion/settings.py distribucion/distribucion/settings.py
RUN chmod +x distribucion/tools/create_db

RUN git clone https://github.com/matiasg/allocation.git
RUN pip install -e allocation
RUN pip install -r allocation/requirements.txt

WORKDIR distribucion

RUN pip install -r requirements.txt
