# Generated by Django 2.1.7 on 2019-04-20 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materias', '0001_initial'),
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intento', models.IntegerField()),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.Carga')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.Turno')),
            ],
            options={
                'verbose_name': 'asignación',
                'verbose_name_plural': 'asignaciones',
            },
        ),
        migrations.CreateModel(
            name='Preferencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_normalizado', models.FloatField()),
                ('preferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.PreferenciasDocente')),
            ],
        ),
    ]
