# Generated by Django 2.1.7 on 2019-03-14 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dborrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacion',
            options={'verbose_name': 'asignación', 'verbose_name_plural': 'asignaciones'},
        ),
    ]
