# Generated by Django 2.1.7 on 2019-04-29 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0006_auto_20190428_2305'),
        ('dborrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('intento', models.IntegerField()),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.Turno')),
            ],
        ),
    ]
