# Generated by Django 2.1.7 on 2019-06-08 21:31

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dborrador', '0002_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='intento',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='intentos',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(default=(0, None)),
            preserve_default=False,
        ),
    ]
