# Generated by Django 2.1.7 on 2019-03-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dborrador', '0002_auto_20190313_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferencia',
            name='peso_normalizado',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
