# Generated by Django 2.1.7 on 2019-06-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dborrador', '0003_auto_20190608_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='cargo_que_ocupa',
            field=models.CharField(choices=[('P', 'Profesor'), ('J', 'JTP'), ('A1', 'Ay1'), ('A2', 'Ay2')], default='J', max_length=2),
            preserve_default=False,
        ),
    ]
