# Generated by Django 2.1.7 on 2019-04-13 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0008_auto_20190411_0045'),
        ('dborrador', '0003_preferencia_peso_normalizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='docente',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='carga',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='materias.Carga'),
            preserve_default=False,
        ),
    ]
