# Generated by Django 2.1.10 on 2019-07-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dborrador', '0004_asignacion_cargo_que_ocupa'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoRegistrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intento', models.IntegerField()),
                ('anno', models.IntegerField()),
                ('cuatrimestre', models.CharField(choices=[('P', '1'), ('S', '2'), ('V', 'V')], max_length=1)),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
