# Generated by Django 2.1.10 on 2019-07-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dborrador', '0005_intentoregistrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intentoregistrado',
            name='cuatrimestre',
            field=models.CharField(choices=[('V', 'V'), ('P', '1'), ('S', '2')], max_length=1),
        ),
    ]
