# Generated by Django 2.1 on 2019-03-05 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materias', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciasDocente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField(null=True)),
                ('anno', models.IntegerField()),
                ('cuatrimestre', models.CharField(choices=[('P', '1'), ('S', '2'), ('V', 'V')], max_length=1)),
                ('fecha_encuesta', models.DateTimeField()),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.Docente')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.Turno')),
            ],
        ),
    ]
