# Generated by Django 2.1.2 on 2019-01-22 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0010_auto_20190111_0031'),
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciasdocente',
            name='docente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='materias.Docente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preferenciasdocente',
            name='peso',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
