# Generated by Django 2.1 on 2019-03-05 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferenciasdocente',
            name='anno',
        ),
        migrations.RemoveField(
            model_name='preferenciasdocente',
            name='cuatrimestre',
        ),
    ]
