# Generated by Django 2.1.7 on 2019-04-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_auto_20190305_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciasdocente',
            name='cargo',
            field=models.CharField(choices=[('Tit', 'Prof. Titular'), ('Aso', 'Prof. Asociado'), ('Adj', 'Prof. Adjunto'), ('JTP', 'Jefe de Trabajos Prácticos'), ('Ay1', 'Ayudante de 1ra'), ('Ay2', 'Ayudante de 2da')], default='Tit', max_length=3),
            preserve_default=False,
        ),
    ]
