# Generated by Django 2.1.2 on 2019-01-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_auto_20190122_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferenciasdocente',
            name='peso',
            field=models.FloatField(null=True),
        ),
    ]
