# Generated by Django 2.1.2 on 2019-01-23 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0010_auto_20190111_0031'),
        ('encuestas', '0003_auto_20190122_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciasdocente',
            name='turno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='materias.Turno'),
            preserve_default=False,
        ),
    ]
