# Generated by Django 2.1.7 on 2019-06-08 21:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0003_otrosdatos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otrosdatos',
            name='telefono',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener +, -, números, espacios y tener longitud de teléfono', regex='^\\+?[0-9 -]{9,15}$')]),
        ),
    ]
