# Generated by Django 2.1.9 on 2019-06-22 20:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0004_auto_20190608_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='otrosdatos',
            name='anno',
            field=models.IntegerField(default=2019),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otrosdatos',
            name='cuatrimestre',
            field=models.CharField(choices=[('P', '1'), ('S', '2'), ('V', 'V')], default='S', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otrosdatos',
            name='telefono',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener +, -, números, espacios y tener entre 9 y 15 caracteres', regex='^\\+?[0-9 -]{9,15}$')]),
        ),
    ]
