# Generated by Django 2.1.6 on 2019-02-14 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0004_preferenciasdocente_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciasdocente',
            name='anno',
            field=models.IntegerField(default=2019),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preferenciasdocente',
            name='cuatrimestre',
            field=models.CharField(choices=[('P', '1'), ('S', '2'), ('V', 'V')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preferenciasdocente',
            name='fecha_encuesta',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
