# Generated by Django 2.1.10 on 2019-07-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0006_auto_20190630_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestasHabilitadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField()),
                ('cuatrimestres', models.CharField(choices=[('V', 'Verano'), ('P', '1'), ('S', '2'), ('VP', 'V. y 1'), ('VPS', 'todos')], max_length=3)),
                ('tipo_docente', models.CharField(choices=[('P', 'Profesor'), ('J', 'JTP'), ('A1', 'Ay1'), ('A2', 'Ay2')], max_length=2)),
                ('desde', models.DateTimeField()),
                ('hasta', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='otrosdatos',
            name='cuatrimestre',
            field=models.CharField(choices=[('V', 'V'), ('P', '1'), ('S', '2')], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='encuestashabilitadas',
            unique_together={('anno', 'cuatrimestres', 'tipo_docente')},
        ),
    ]
