# Generated by Django 2.1.10 on 2019-07-19 02:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0012_auto_20190717_0021'),
        ('encuestas', '0007_auto_20190717_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargasPedidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField()),
                ('cuatrimestre', models.CharField(choices=[('V', 'V'), ('P', '1'), ('S', '2')], max_length=1)),
                ('cargas', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3)])),
                ('fecha_encuesta', models.DateTimeField()),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.Docente')),
            ],
        ),
        migrations.RemoveField(
            model_name='otrosdatos',
            name='cargas',
        ),
    ]
