# Generated by Django 2.1.10 on 2019-07-23 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0008_auto_20190718_2351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encuestashabilitadas',
            options={'ordering': ['anno', 'tipo_docente']},
        ),
    ]
