# Generated by Django 2.1.10 on 2019-10-07 00:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0009_auto_20190722_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargasDeclaradas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaradas', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(6)])),
                ('otros_datos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.OtrosDatos')),
            ],
        ),
    ]
