# Generated by Django 2.1.10 on 2019-10-07 01:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0010_cargasdeclaradas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargasdeclaradas',
            name='otros_datos',
        ),
        migrations.AddField(
            model_name='otrosdatos',
            name='cargas_declaradas',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.DeleteModel(
            name='CargasDeclaradas',
        ),
    ]
