# Generated by Django 2.1.10 on 2019-10-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0012_auto_20191026_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otrosdatos',
            name='cuatrimestre',
            field=models.CharField(choices=[('V', 'Verano'), ('P', '1'), ('S', '2'), ('VP', 'V. y 1'), ('VPS', 'todos')], max_length=3),
        ),
    ]
