# Generated by Django 2.1.10 on 2019-10-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0013_auto_20191027_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargaspedidas',
            name='tipo_docente',
            field=models.CharField(choices=[('P', 'Profesor'), ('J', 'JTP'), ('A1', 'Ay1'), ('A2', 'Ay2')], default='P', max_length=2),
            preserve_default=False,
        ),
    ]
