# Generated by Django 2.1.11 on 2019-11-23 20:27

from django.db import migrations, models
from encuestas.models import CargasPedidas


def agrega_tipo(apps, schema_editor):
    PreferenciasDocente = apps.get_model('encuestas', 'PreferenciasDocente')
    for preferencia in PreferenciasDocente.objects.all():
        od = CargasPedidas.objects.filter(docente__pk=preferencia.docente.id, fecha_encuesta=preferencia.fecha_encuesta).first()
        preferencia.tipo_docente = od.tipo_docente
        preferencia.save()


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0014_cargaspedidas_tipo_docente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otrosdatos',
            options={'ordering': ['fecha_encuesta']},
        ),
        migrations.RemoveField(
            model_name='historicalpreferenciasdocente',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='preferenciasdocente',
            name='cargo',
        ),
        migrations.AddField(
            model_name='historicalpreferenciasdocente',
            name='tipo_docente',
            field=models.CharField(choices=[('P', 'Profesor'), ('J', 'JTP'), ('A1', 'Ay1'), ('A2', 'Ay2')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preferenciasdocente',
            name='tipo_docente',
            field=models.CharField(choices=[('P', 'Profesor'), ('J', 'JTP'), ('A1', 'Ay1'), ('A2', 'Ay2')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.RunPython(agrega_tipo),
    ]
