# Generated by Django 2.1.11 on 2019-12-08 12:27

from django.db import migrations, models
from encuestas.models import CargasPedidas

def corrige_tipo(apps, schema_editor):
    OtrosDatos = apps.get_model('encuestas', 'OtrosDatos')
    for otros_datos in OtrosDatos.objects.all():
        cp = CargasPedidas.objects.filter(docente__pk=otros_datos.docente.id,
                                          fecha_encuesta=otros_datos.fecha_encuesta).first()
        otros_datos.tipo_docente = cp.tipo_docente
        otros_datos.save()


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0015_auto_20191123_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='otrosdatos',
            name='tipo_docente',
            field=models.CharField(choices=[('P', 'Profesor'), ('J', 'JTP'), ('A1', 'Ay1'), ('A2', 'Ay2')], default='??', max_length=2),
            preserve_default=False,
        ),
        migrations.RunPython(corrige_tipo),
   ]
